### ISSUE TITLE
mlJobRepo installation fails with "Password is too weak"

### ISSUE THREAD

**Issue by fsnow** [marklogic-community/marklogic-spring-batch#275]
ML 9.0-3.1, Windows. Latest mlJobRepo distro. (1.4.1). Interestingly, did not get this error when I ran the installation on same ML version on my Mac.

Fails when creating the spring-batch-admin user.

./mlJobRepo.bat --host localhost --port 8201 --name mlJobRepo --username admin --password admin --debug

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/F:/apps/mlJobRepo-1.4.0/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/F:/apps/mlJobRepo-1.4.0/lib/logback-classic-1.1.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
0    [main] INFO  com.marklogic.mgmt.ManageClient  - Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
583  [main] INFO  com.marklogic.mgmt.ManageClient  - Sending XML GET request as user with admin role 'admin' to path: /manage/v2/roles
892  [main] INFO  com.marklogic.mgmt.resource.security.RoleManager  - Found role with name of spring-batch-reader, so updating at path /manage/v2/roles/spring-batch-reader/properties
892  [main] INFO  com.marklogic.mgmt.ManageClient  - Sending JSON PUT request as user with admin role 'admin' to path: /manage/v2/roles/spring-batch-reader/properties
1202 [main] INFO  com.marklogic.mgmt.resource.security.RoleManager  - Updated role at /manage/v2/roles/spring-batch-reader/properties
1203 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending XML GET request as user with admin role 'admin' to path: /manage/v2/roles
1331 [main] INFO  com.marklogic.mgmt.resource.security.RoleManager  - Found role with name of spring-batch-admin, so updating at path /manage/v2/roles/spring-batch-admin/properties
1331 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending JSON PUT request as user with admin role 'admin' to path: /manage/v2/roles/spring-batch-admin/properties
1507 [main] INFO  com.marklogic.mgmt.resource.security.RoleManager  - Updated role at /manage/v2/roles/spring-batch-admin/properties
1510 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending XML GET request as user with admin role 'admin' to path: /manage/v2/users
1544 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending XML GET request as user with admin role 'admin' to path: /manage/v2/users
1582 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending JSON GET request as user 'admin' to path: /manage/v2/users/spring-batch-admin/properties
1681 [main] INFO  com.marklogic.mgmt.api.security.User  - Saving user spring-batch-admin
1696 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending XML GET request as user with admin role 'admin' to path: /manage/v2/users
1729 [main] INFO  com.marklogic.mgmt.resource.security.UserManager  - Found user with name of spring-batch-admin, so updating at path /manage/v2/users/spring-batch-admin/properties
1729 [main] INFO  com.marklogic.mgmt.ManageClient  - Sending JSON PUT request as user with admin role 'admin' to path: /manage/v2/users/spring-batch-admin/properties
1768 [main] ERROR com.marklogic.rest.util.MgmtResponseErrorHandler  - Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"SEC-REJECTEDPWD", "message":"SEC-REJECTEDPWD: (err:FOER0000) Password is too weak"}}
Exception in thread "main" org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
        at com.marklogic.rest.util.MgmtResponseErrorHandler.handleError(MgmtResponseErrorHandler.java:20)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:549)
        at com.marklogic.mgmt.ManageClient.putJsonAsAdmin(ManageClient.java:89)
        at com.marklogic.mgmt.AbstractManager.putPayload(AbstractManager.java:50)
        at com.marklogic.mgmt.resource.AbstractResourceManager.updateResource(AbstractResourceManager.java:139)
        at com.marklogic.mgmt.resource.AbstractResourceManager.save(AbstractResourceManager.java:86)
        at com.marklogic.mgmt.api.Resource.save(Resource.java:51)
        at com.marklogic.spring.batch.MarkLogicSimpleJobRepositoryAppDeployer.deploy(MarkLogicSimpleJobRepositoryAppDeployer.java:37)
        at com.marklogic.spring.batch.DeployMarkLogicJobRepository.deployMarkLogicJobRepository(DeployMarkLogicJobRepository.java:43)
        at com.marklogic.spring.batch.DeployMarkLogicJobRepository.run(DeployMarkLogicJobRepository.java:35)
        at com.marklogic.spring.batch.DeployMarkLogicJobRepository.main(DeployMarkLogicJobRepository.java:24)

**Comment by sastafford** [comment]
merged with #277
